language: node_js
node_js:
  - "0.10"

env:
  global:
    - SAUCE_USERNAME=gregorypratt
    - SAUCE_ACCESS_KEY=d923613e-2797-4046-b0db-efdf3e9a205b

addons:
  sauce_connect: true

before_install:
  - npm install -g grunt-cli

install:
  - webdriver-manager update